config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  namespace :account do
    resource :owner
  end
  resources :posts do
    resources :comments
  end

end

app/models/account.rb
module Account
  def self.table_name_prefix
    'account_'
  end
end

app/models/account/owner.rb
class Account::Owner < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: :comments_count
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :blog_owner, class_name: "User", foreign_key: :user_id
  has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_one :owner, class_name: "Account::Owner", foreign_key: :user_id
end

app/controllers/account/owners_controller.rb
class Account::OwnersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def new
    @account_owner = current_user.build_owner
  end

  def create
    @account_owner = current_user.create_owner(profile_params)

    if @account_owner.save
      puts "aaaa"
      redirect_to posts_path, notice: "新增個人自介成功！"
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  def show
    @account_owner = User.find(1).owner
  end

  private

  def profile_params
    params.require(:account_owner).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]
  before_action :find_post

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to post_path(@post), notice: "新增評論成功！"
    else
      render :new
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post), alert: "刪除評論成功"
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, except: [:index, :new, :create, :show]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: "新增文章成功！"
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def edit
  end

  def update

    if @post.update(post_params)
      redirect_to posts_path, ud: "更新文章成功～"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, alert: "刪除文章成功～"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_post
    @post = current_user.posts.find(params[:id])
  end
end

app/helpers/account/owners_helper.rb
module Account::OwnersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = {notice: :success, alert: :danger, ud: :warning}

    close_button_options = {class: "close", "data-dismiss" => "alert", "aria-hidden" => true}
    close_button = content_tag(:button, "x", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = {class: "alert alert-#{alert_type} alert-dismissable"}

      content_tag(:div, alert_content, alert_class)
    end

    alerts.join("\n").html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>新增評論</h1>
  <hr>

  <%= simple_form_for [@post, @comment] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."} %>
  <% end %>
</div>

app/views/common/_footer.html.erb
<footer class="container-fluid" style="margin-top: 100px;">
  <p class="text-center">Design by<a href="rorusage@gmail.com"></a> Rorusage</p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type = "button" class = "navbar-toggle" data-toggle = "collapse" data-target = "#example-navbar-collapse">
      <span class="sr-only">Toggle</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <% if current_user %>
      <a href="/" class="navbar-brand"> Rorusage's blog</a>
    <% else %>
      <a href="/" class="navbar-brand"> Blog </a>
    <% end %>
  </div>

  <div id="example-navbar-collapse" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <% if !current_user %>
        <!-- <li><%= link_to("註冊", new_user_registration_path) %></li> -->
        <li><%= link_to("登入", new_user_session_path) %></li>
      <% else %>
        <li><%= link_to("New Post", new_post_path, class: "btn btn-primary pull-right") %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi, <%= current_user.name %>
          <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to("帳號設定", edit_user_registration_path) %></li>
            <li><%= link_to("新增個人介紹", new_account_owner_path)%></li>
            <li><%= link_to("編輯個人介紹", edit_account_owner_path) %></li>
            <li><%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render "common/navbar" %>
  <div class="row">
    <div class="col-md-4">
      <ul class="list-group">
        <li class="list-group-item"><%= link_to("About Me", account_owner_path, method: :get) %></li>
        <li class="list-group-item">Facebook</li>
        <li class="list-group-item">Twitter</li>
        <li class="list-group-item"><%= link_to("Show all posts", posts_path)%></li>
      </ul>
    </div>

    <div class="col-md-8">
      <%= notice_message %>
      <%= yield %>
    </div>
  </div>
</div>

<%= render "common/footer" %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>修改文章</h1>
  <hr>

  <%= simple_form_for @post do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: {class: "form-control"} %>
      <%= f.input :content, input_html: {class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."} %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="col-md-12">
<!--   <div class="group">
    <%= link_to("New Post", new_post_path, class: "btn btn-primary pull-right")%>
  </div>
 -->
  <% @posts.each do |post| %>
    <h3><%= link_to(post.title, post_path(post)) %></h3>
    <% if current_user == post.blog_owner %>
      <%= link_to("Edit", edit_post_path(post), class: "btn btn-primary") %>
      <%= link_to("Delete", post_path(post), class: "btn btn-primary",
                  method: :delete, data: {confirm: "Are you sure?"}) %>
    <% end %>
    <br>
    <p><%= post.created_at.strftime("Submitted at %B %-d, %Y")%></p>
    <%= truncate(post.content)%>
    <hr>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>新增文章</h1>
  <hr>

  <%= simple_form_for @post do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: {class: "form-control" }%>
      <%= f.input :content, input_html: {class: "form-control" }%>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."}%>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">
  <div class="group">
    <% if current_user == @post.blog_owner%>
      <%= link_to("Edit", edit_post_path, class: "btn btn-primary pull-right")%>
    <% end %>
  </div>
  <h2><%= @post.title %></h2>
  <p>Submitted <%= time_ago_in_words(@post.created_at)%> ago</p>
  <p><%= @post.content %></p>
  <hr>

  <%= link_to("Comment", new_post_comment_path(@post), class: "btn btn-primary pull-right")%>
  <br>
  <h3><%= @post.comments.size %> Comments:</h3>
  <br>
  <% @comments.each do |comment| %>
    <h4><%= comment.content %></h4>
    <% if current_user == @post.blog_owner %>
      <%= link_to("Delete", post_comment_path(comment.post, comment), method: :delete, class: "btn btn-danger pull-right")%>
    <% end %>
  <% end %>
  <%= link_to("Back", posts_path, class: "btn btn-info")%>
</div>